### ISSUE TITLE
PDF rendering issues

### ISSUE THREAD

**Issue by LorenzBuehmann** [gephi/gephi-toolkit#15]
Hi,

I'm working on the 0.9-SNAPHOT version, and can't get it working to correctly export a GraphML-based file to PDF. 

1) the edge arrows aren't visible although the graph consists of only directed edges
2) the node boxes always hide most of the node labels. 
I tried to disable the boxes with

``` Java
model.getProperties().putValue(PreviewProperty.NODE_LABEL_SHOW_BOX, false)
```

 but it doesn't work.

It's also not clear how to setup the property which is used as node label(resp. edge label). For now I set those values manually after import to edge node and edge object contained in the graph.

I attached the graphML file and the corresponding PDF

[rdfs2.graphml.txt](https://github.com/gephi/gephi-toolkit/files/106515/rdfs2.graphml.txt)
[rdfs2.graphml.pdf](https://github.com/gephi/gephi-toolkit/files/106509/rdfs2.graphml.pdf)

**Comment by mbastian** [comment]
Hi @LorenzBuehmann I'm closing old issues here. Apologies for the lack of reply.
