### ISSUE TITLE
EdgePartitionFilter NullPointerException in  selectAll() and evaluate()

### ISSUE THREAD

**Issue by YHRen** [gephi/gephi-toolkit#17]
Dear, Sir,

I encountered an exception when I am trying to develop EdgePartitionFilter,
following the example from https://github.com/gephi/gephi-toolkit-demos/blob/master/src/main/java/org/gephi/toolkit/demos/Filtering.java .

if I unselecteAll() and addPart(), there will be no Exception, BUT,
the graph is not filtered at all (nodeCount and edgeCount won't change.)
Then, I tried to selectAll() and removePart(), the NullPointerException has been thrown.
I am sure the attribute is there as I iterated through all edges and output their attribute values.

I think it might be a bug.
Could you please have a look?

Thank you so much.
Best wishes,
Yihui

Here is the error message. 
(I tried both Java 7 and 8. I tired both 0.9 release version and 0.92 nightly snapshot)

Exception in thread "main" java.lang.NullPointerException
    at org.gephi.filters.plugin.partition.PartitionBuilder$PartitionFilter.selectAll(PartitionBuilder.java:269)
    at HelloGephi.main(HelloGephi.java:130)

**Comment by loveneet29** [comment]
Have you find the solution for your problem.
As i am also facing same issue with partition filter

**Comment by mbastian** [comment]
Hi @YHRen I'm closing old issues. Apologies for the lack of reply. I can no longer reproduce this issue so I think it got fixed in version 0.9.3+.
