### ISSUE TITLE
gephi visualization module under FreeBSD

### ISSUE THREAD

**Issue by apophys0** [gephi/gephi-toolkit#19]
Greetings.
I am trying to run gephi under FreeBSD. Regardless of running the ready to go version or building gephi myself, after showing the window, there is still this problem about
not being able to initialize jogamp-jogl (see latest caught error down below). Consequence of this: no graph visualization.
I have managed to narrow it down to the fact that gephi comes pre-bundled with

./modules/application/target/gephi/gephi/modules/ext/org.gephi.visualization/
├── org-jogamp-gluegen
│   ├── gluegen-rt-natives-linux-amd64.jar
│   ├── gluegen-rt-natives-linux-i586.jar
│   ├── gluegen-rt-natives-macosx-universal.jar
│   ├── gluegen-rt-natives-windows-amd64.jar
│   ├── gluegen-rt-natives-windows-i586.jar
│   └── gluegen-rt.jar
└── org-jogamp-jogl
    ├── jogl-all-natives-linux-amd64.jar
    ├── jogl-all-natives-linux-i586.jar
    ├── jogl-all-natives-macosx-universal.jar
    ├── jogl-all-natives-windows-amd64.jar
    ├── jogl-all-natives-windows-i586.jar
    └── jogl-all.jar

As for FreeBSD, we can install the port "graphics/jogl"  or "graphics/jogamp-jogl". I did install "graphics/jogamp-jogl" (because it has as project homepage: http://jogamp.org/jogl) which brings
jogamp-jogl-2.2.4_1:
        /usr/local/lib/libgluegen2-rt.so
        /usr/local/lib/libjogl_cg.so
        /usr/local/lib/libjogl_desktop.so
        /usr/local/lib/libjogl_mobile.so
        /usr/local/lib/libnativewindow_awt.so
        /usr/local/lib/libnativewindow_x11.so
        /usr/local/lib/libnewt.so
        /usr/local/share/java/classes/gluegen2-rt.jar
        /usr/local/share/java/classes/gluegen2.jar
        /usr/local/share/java/classes/jogl2.jar

So, my question is: what is the proper way to bind gephi to my native jogl?

---------

PS: The announced latest caught error:

[INFO] SEVERE [org.netbeans.core.modules]
[INFO] java.lang.UnsatisfiedLinkError: Can't load library: ./gephi/modules/application/natives/freebsd-amd64//libgluegen-rt.so
[INFO]  at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1827)
[INFO]  at java.lang.Runtime.load0(Runtime.java:809)
[INFO]  at java.lang.System.load(System.java:1086)
[INFO]  at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:624)
[INFO]  at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:63)
[INFO]  at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:106)
[INFO]  at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:487)
[INFO]  at com.jogamp.common.os.DynamicLibraryBundle$GlueJNILibLoader.loadLibrary(DynamicLibraryBundle.java:421)
[INFO]  at com.jogamp.common.os.Platform$1.run(Platform.java:317)
[INFO]  at java.security.AccessController.doPrivileged(Native Method)
[INFO]  at com.jogamp.common.os.Platform.<clinit>(Platform.java:287)
[INFO]  at com.jogamp.opengl.GLProfile.<clinit>(GLProfile.java:147)
[INFO]  at org.gephi.visualization.Installer.restored(Installer.java:55)
[INFO]  at org.netbeans.core.startup.NbInstaller.loadCode(NbInstaller.java:468)
 
--------- .

**Comment by eduramiba** [comment]
Hi, I don't think jogl supports freebsd, specially when there are many problems with graphic drivers even on Linux.

**Comment by eduramiba** [comment]
Adding to wishlist for investigation

**Comment by eduramiba** [comment]
What version are you using of Gephi? Also I understand this is an issue of Gephi desktop and not toolkit.
Now, with 0.9.1 we include jogl 2.3.1 and I'm not sure but it might include freebsd natives.

**Comment by apophys0** [comment]
I built "Gephi 0.9.2-SNAPSHOT 201701291332". What is include within is:
./modules/application/target/gephi/gephi/modules/ext/org.gephi.visualization/
├── org-jogamp-gluegen
│   ├── gluegen-rt-natives-linux-amd64.jar
│   ├── gluegen-rt-natives-linux-i586.jar
│   ├── gluegen-rt-natives-macosx-universal.jar
│   ├── gluegen-rt-natives-windows-amd64.jar
│   ├── gluegen-rt-natives-windows-i586.jar
│   └── gluegen-rt.jar
└── org-jogamp-jogl
├── jogl-all-natives-linux-amd64.jar
├── jogl-all-natives-linux-i586.jar
├── jogl-all-natives-macosx-universal.jar
├── jogl-all-natives-windows-amd64.jar
├── jogl-all-natives-windows-i586.jar
└── jogl-all.jar

**Comment by eduramiba** [comment]
Unfortunately there are no freebsd natives deployed to maven for JOGL. See:

* http://central.maven.org/maven2/org/jogamp/gluegen/gluegen-rt/2.3.2
* http://central.maven.org/maven2/org/jogamp/jogl/jogl-all/2.3.2

Do you know if these are available anywhere? (must be version 2.3.2).

**Comment by apophys0** [comment]
Hi eduramiba, and my apology for the silence; actuallyu I have been trying to find a good answer for you. In a nutshell:

  1- I could not find a repository with those natives;

  2- After understanding that there was a pom.xml in gephi sources listing those 
        natives as dependencies, I went looking for a way to at least build the native JARs 
        and point the pom.xml to those. I am still trying to do so (BTW, I emailed the jogamp, 
        seeking help on the matter; still waiting for an answer.).

That is all I have for now.

**Comment by eduramiba** [comment]
Closing as not supported by JOGL
