### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by tkuhn** [gephi/gephi-toolkit#2]
I am getting a "BUILD FAILURE" from Maven. This is the error message:

```
Failed to collect dependencies for [junit:junit:jar:3.8.1 (test), org.gephi:gephi-toolkit:jar:0.9-SNAPSHOT (compile)]: Failed to read artifact descriptor for org.gephi:utils-longtask:jar:0.9-SNAPSHOT: Could not find artifact org.gephi:gephi-parent:pom:0.9-SNAPSHOT in gephi-snapshots (http://nexus.gephi.org/nexus/content/repositories/snapshots/)
```

I think it's because there is no jar file in this directory: http://nexus.gephi.org/nexus/content/repositories/public/org/gephi/gephi-parent/0.9-SNAPSHOT/

The same problem has been reported here: https://forum.gephi.org/viewtopic.php?f=27&t=2560

**Comment by andralungu** [comment]
Hi, I simply cloned the main repo and executed `mvn clean install` on it. Nevertheless, I get the following error:

[ERROR] Failed to execute goal on project gephi-toolkit: Could not resolve dependencies for project org.gephi:gephi-toolkit:jar:0.9-SNAPSHOT: Failed to collect dependencies for [org.netbeans.api:org-netbeans-modules-nbjunit:jar:RELEASE721 (test), org.netbeans.modules:org-netbeans-modules-masterfs:jar:RELEASE721 (compile), org.netbeans.modules:org-netbeans-core-startup:jar:RELEASE721 (compile), org.netbeans.modules:org-netbeans-core:jar:RELEASE721 (compile), org.gephi:utils-longtask:jar:0.9-SNAPSHOT (compile), org.gephi:project-api:jar:0.9-SNAPSHOT (compile), org.gephi:io-exporter-api:jar:0.9-SNAPSHOT (compile), org.gephi:graph-api:jar:0.9-SNAPSHOT (compile), org.gephi:data-attributes-api:jar:0.9-SNAPSHOT (compile), org.gephi:preview-api:jar:0.9-SNAPSHOT (compile), org.gephi:io-exporter-preview:jar:0.9-SNAPSHOT (compile), org.gephi:dynamic-api:jar:0.9-SNAPSHOT (compile), org.gephi:utils:jar:0.9-SNAPSHOT (compile), org.gephi:datalab-api:jar:0.9-SNAPSHOT (compile), org.gephi:visualization-api:jar:0.9-SNAPSHOT (compile), org.gephi:preview-plugin:jar:0.9-SNAPSHOT (compile), org.gephi:db-drivers:jar:0.9-SNAPSHOT (compile), org.gephi:io-importer-api:jar:0.9-SNAPSHOT (compile), org.gephi:io-processor-plugin:jar:0.9-SNAPSHOT (compile), org.gephi:ranking-api:jar:0.9-SNAPSHOT (compile), org.gephi:ranking-plugin:jar:0.9-SNAPSHOT (compile), org.gephi:spigot-plugin:jar:0.9-SNAPSHOT (compile), org.gephi:statistics-api:jar:0.9-SNAPSHOT (compile), org.gephi:statistics-plugin:jar:0.9-SNAPSHOT (compile), org.gephi:timeline:jar:0.9-SNAPSHOT (compile), org.gephi:algorithms-plugin:jar:0.9-SNAPSHOT (compile), org.gephi:utils-collection:jar:0.9-SNAPSHOT (compile), org.gephi:mostrecentfiles-api:jar:0.9-SNAPSHOT (compile), org.gephi:layout-api:jar:0.9-SNAPSHOT (compile), org.gephi:io-generator-api:jar:0.9-SNAPSHOT (compile), org.gephi:io-generator-plugin:jar:0.9-SNAPSHOT (compile), org.gephi:io-exporter-plugin:jar:0.9-SNAPSHOT (compile), org.gephi:filters-api:jar:0.9-SNAPSHOT (compile), org.gephi:clustering-api:jar:0.9-SNAPSHOT (compile), org.gephi:ui-propertyeditor:jar:0.9-SNAPSHOT (compile), org.gephi:layout-plugin:jar:0.9-SNAPSHOT (compile), org.gephi:partition-api:jar:0.9-SNAPSHOT (compile), org.gephi:graph-dhns:jar:0.9-SNAPSHOT (compile), org.gephi:attributes:jar:0.9-SNAPSHOT (compile), org.gephi:io-importer-plugin:jar:0.9-SNAPSHOT (compile), org.gephi:filters-plugin:jar:0.9-SNAPSHOT (compile), org.gephi:filters-impl:jar:0.9-SNAPSHOT (compile), org.gephi:dynamic-impl:jar:0.9-SNAPSHOT (compile), org.gephi:partition-plugin:jar:0.9-SNAPSHOT (compile), org.gephi:clustering-plugin:jar:0.9-SNAPSHOT (compile), org.gephi:core-library-wrapper:jar:0.9-SNAPSHOT (compile)]: Failed to read artifact descriptor for org.gephi:utils-longtask:jar:0.9-SNAPSHOT: Failure to find org.gephi:gephi-parent:pom:0.9-SNAPSHOT in http://bits.netbeans.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of netbeans has elapsed or updates are forced -> [Help 1]

Am I doing something wrong?
Thanks!

**Comment by mbastian** [comment]
Hi, do you still have this issue? We've just moved the location of artifacts from our private Nexus server to Sonatype (oss.sonatype.org) and it should be working fine for everyone.

Here is a pom example:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.gephi</groupId>
    <artifactId>toolkit-example</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <repositories>
        <repository>
            <id>oss-sonatype</id>
            <name>oss-sonatype</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.gephi</groupId>
            <artifactId>gephi-toolkit</artifactId>
            <version>0.9-SNAPSHOT</version>
        </dependency>
    </dependencies>
</project>
```

**Comment by tomlue** [comment]
I am still getting this issue when using 
    <groupId>org.gephi</groupId>
    <artifactId>toolkit-example</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
The module cannot be found at the sonatype repositories.

**Comment by eduramiba** [comment]
Closing old issue.

**Comment by kblinichkin** [comment]
The same issue happened while building gephi-app 0.9.7-SNAPSHOT.
