### ISSUE TITLE
Set node color

### ISSUE THREAD

**Issue by nh3** [gephi/gephi-toolkit#21]
Apologies that this is not an issue but a question. I tried emailing contact@gephi.org but have received no reply.

The question is: is there a way to set the color of all nodes (regardless of any attribute)? There isn't a field in `PreviewProperty` for node color as there is for edge color (`EDGE_COLOR`). I guess perhaps I need to use `UniqueElementColorTransformer`, and I tried the following:

    Function simpleNodeColor = appearanceModel.getNodeFunction(graph, AppearanceModel.GraphFunction.NODE_DEGREE, UniqueElementColorTransformer.class);
    UniqueElementColorTransformer nodeColorTransformer = (UniqueElementColorTransformer) simpleNodeColor.getTransformer();
    nodeColorTransformer.setColor(Color.GRAY);
    appearanceController.transform(simpleNodeColor);

However, the second line always give me a NullPointerException. I'd really appreciate if you could give me some clues or example code. Thanks a lot!

**Comment by eduramiba** [comment]
You can just iterate all nodes in the graph and set their color: https://gephi.org/gephi/0.9.1/apidocs/org/gephi/graph/api/ElementProperties.html#setColor-java.awt.Color-
