### ISSUE TITLE
Filter labels of graph using gephi-toolkit-0.9.1

### ISSUE THREAD

**Issue by mari-mari** [gephi/gephi-toolkit#22]
Hi, I would like the resulting graph to contain all nodes, but to show labels only for those with degree>1000.
Call of `exportToLabelVisible(query)` changes labels of nodes to be not visible (`node.isVisible()` is false), but the resulting graph in the file still has labels for all the nodes. 
```java
FilterController filterController = Lookup.getDefault().lookup(FilterController.class); 
DegreeRangeFilter degreeFilter = new DegreeRangeFilter(); 
degreeFilter.init(graphModel.getGraph()); 
degreeFilter.setRange(new Range(1000, Integer.MAX_VALUE));     
Query query = filterController.createQuery(degreeFilter); 
       
 
filterController.exportToLabelVisible(query);
//filterController.filterVisible(query);
   
GraphView view = graphModel.getGraphVisible().getView();             
graphModel.setVisibleView(view);
  

PNGExporter pngExporter = (PNGExporter) ec.getExporter("png");
ec.exportFile(new File("FILE.png"), pngExporter);
```
I know how to do that in desktop app, but really stuck with the toolkit. I would appreciate any help.

**Comment by eduramiba** [comment]
I think you will need to refresh preview with the preview controller before export

**Comment by mari-mari** [comment]
Thanks for the reply. 
I tried refreshing preview, did not work for me :/ 
```java
filterController.exportToLabelVisible(query);
GraphView view = graphModel.getGraphVisible().getView();             
graphModel.setVisibleView(view);
Lookup.getDefault().lookup(PreviewController.class).refreshPreview(workspace);
```
However, I solved the problem in a pretty dirty way, by iterating through all nodes and setting labels to empty string if a nodes' textProperties set to not visible:
```java
NodeIterable nodes = graphModel.getGraph().getNodes();

filterController.exportToLabelVisible(query);
for (Node n : nodes) {
    if (!n.getTextProperties().isVisible()) {
        n.setLabel("");
    } 
}
//here goes export
```

**Comment by eduramiba** [comment]
Right, this is the correct approach with visible labels.
