### ISSUE TITLE
Where can I find The class DynamicModel and AttributeModel

### ISSUE THREAD

**Issue by Alvinsjq** [gephi/gephi-toolkit#25]
I am trying to run the toolkit-demo program and wanna implement a dynamic graph.

So, I have found the website How to execute a metric over time and learn to run it.
However, I found that is different from the code in the file DynamicMetric in toolkit-demo. And I cannot find the class **DynamicModel** and **AttributeModel**.
**Are these classes not in the toolkit?**

Thank you for your help!

**Comment by eduramiba** [comment]
Duplicate of https://github.com/gephi/gephi/issues/1884
