### ISSUE TITLE
How do I use dynamic edges

### ISSUE THREAD

**Issue by Jonty800** [gephi/gephi-toolkit#27]
Using the toolkit, how do I create a graph with dynamic edges, which change weight over time?

`edge.setWeight(weight, interval);`

> Can't use timestamps as the configuration is set to INTERVAL

**Comment by eduramiba** [comment]
Hi,
I think you need to get the graphstore ```Configuration``` from the ```graphModel``` and set ```TimeRepresentation``` to ```TIMESTAMP```

That must be done before adding any data to the graph.

https://gephi.org/graphstore/apidocs/org/gephi/graph/api/GraphModel.html
https://gephi.org/graphstore/apidocs/org/gephi/graph/api/Configuration.html

**Comment by gpf951101** [comment]
I have the same problem, can you give me an example? Thanks!

**Comment by gpf951101** [comment]
> Using the toolkit, how do I create a graph with dynamic edges, which change weight over time?
> 
> `edge.setWeight(weight, interval);`
> 
> > Can't use timestamps as the configuration is set to INTERVAL

Can u tell me how did u do to achieve it?
