### ISSUE TITLE
VisualizationController getSelectedEdges()/getSelectedNodes()

### ISSUE THREAD

**Issue by jbliesener** [gephi/gephi-toolkit#28]
Is there a way to get the currently selected edges or nodes in a graph? 

I see that SelectionManager has a method getSelectedNodes(), but SelectionManager is not a public interface (I'd have to cast VisualizationController to VizController and call getSelectionManager to get it). 

But then, SelectionManager lacks a getSelectedEdges() method...

Also, VisualizationController does not have any listeners that would allow me to keep track when edges are selected or deselected.

I need this for my "Average weight of selected edges" statistics plugin...

Any clue? Thank you!

**Comment by eduramiba** [comment]
Hi,
getSelectedEdges is not implemented in the current version, and the VizController is exposed though not in a modular way.

This will change in a future release, as I am re-implementing the whole visualization module from scratch, in a reusable and extensible way.

**Comment by mbastian** [comment]
Hi @jbliesener I'm cleaning up old issues on the toolkit. I think this one is resolved, see https://github.com/gephi/gephi/commit/38fcedeb55ccf2120afebd906d871c61e381e048
