### ISSUE TITLE
Unable to import GraphML (.gml) file for preview 

### ISSUE THREAD

**Issue by SOUMAJYOTI** [gephi/gephi-toolkit#32]
I tried to call the PreviewJFrame script in https://github.com/gephi/gephi-toolkit-demos/blob/master/src/main/java/org/gephi/toolkit/demos/PreviewJFrame.java

directly using the below .gml file, but on executing, it shows # Nodes loaded:0 #  Edges loaded: 0, when actually my toy file contains 1 node as can be seen.

I have attached the .gml file for reproducing here below:

```
<?xml version="1.0" encoding="UTF-8"?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
<graph id="G" edgedefault="directed">
<node id="n0" labels=":Host"><data key="labels">:Host</data><data key="portName">H1</data><data key="maxInDeg">0</data><data key="available">0</data><data key="maxOutDeg">0</data></node>
</graph>
</graphml>
```

**Comment by edward1958** [comment]
Hi! I have text network output files in xml and would like to import them into Gephi to generate graphs and statistics. Can I convert the xml file to gexf or is there another preferred method? Any guidance is appreciated. Thanks a bunch! Ed

**Comment by mbastian** [comment]
Closing old issues. Sorry for the lack of reply.

For reference,
@SOUMAJYOTI: Seems like your input file is a GraphML, not a GML. That probably is why it's not working.
@edward1958 It depends what you want to do but we don't offer any out-of-the-box XML conversion.
