### ISSUE TITLE
Oracle Driver plugin: import with SID

### ISSUE THREAD

**Issue by OlexaRiznyk** [gephi/gephi-toolkit#33]
I'm trying to use Oracle Driver plugin on Windows x64. To connect to my DB, I need to specify Hostname, Port and _SID_ (as I do in Oracle SQL Developer), but Gephi's Database settings window allows to enter Host, Port and _Database_.
If I try to enter my SID into Database field, and press Test Connection, nothing happens.
(I have downloaded Instant Client, unzipped it, set $JDBC_PATH and $ORACLE_HOME to its folder, and restarted Gephi).

How to import from Oracle database using SID?

**Comment by HRTanjuang** [comment]
I am using Oracle DB 19c version 19.9 and Gephi 0.9.2.
JDBC_PATH doesn't work for me, I removed it.
I set ORACLE_HOME to Oracle Instant Client (version 19.9) directory... and it works!
(https://www.oracle.com/database/technologies/instant-client/winx64-64-downloads.html)

Please see "message.log" file in C:\Users\<UserOS>\AppData\Roaming\.gephi\0.9.2\dev\var\log directory.

**Comment by mbastian** [comment]
Closing old issues. Apologies for the lack of reply. In general, we're not able to offer support on the Oracle JDBC connection.
