### ISSUE TITLE
Jigsaw support: split package org.gephi.graph.api

### ISSUE THREAD

**Issue by htmoia** [gephi/gephi-toolkit#40]
When using a module description like
```java
module mymodule{
    requires graphstore;
    requires graph.api;
}
```
you get the following compile error: _Module 'mymodule' reads package 'org.gephi.graph.api' from both 'graphstore' and 'graph.api'_

Are there any workarounds for this issue? Will there be a Java 9 support in the near future?

**Comment by eduramiba** [comment]
Hi, Java 9+ is not supported yet by Gephi and also not modularized. Java 9 + will be supported in the future, but jigsaw modularization is not sure yet.

**Comment by htmoia** [comment]
Ok, thanks for the fast reply!
