### ISSUE TITLE
Cannot resolve dependencies due to RELEASE82 being unavailable on bit.netbeans.org

### ISSUE THREAD

**Issue by htmoia** [gephi/gephi-toolkit#42]
Cloning this repository and running a
```
mvn install
```
currently fails with the following message:

`
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11:10 min
[INFO] Finished at: 2020-05-15T10:41:37+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project gephi-toolkit: Could not resolve dependencies for project org.gephi:gephi-toolkit:jar:0.9.3-SNAPSHOT: The following artifacts could not be resolved: org.netbeans.api:org-netbeans-modules-nbjunit:jar:RELEASE82, org.netbeans.modules:org-netbeans-modules-masterfs:jar:RELEASE82, org.netbeans.modules:org-netbeans-core-startup-base:jar:RELEASE82, org.netbeans.modules:org-netbeans-core:jar:RELEASE82, org.netbeans.api:org-openide-util-lookup:jar:RELEASE82, org.netbeans.api:org-openide-util:jar:RELEASE82, org.netbeans.api:org-openide-filesystems:jar:RELEASE82, org.netbeans.api:org-openide-util-ui:jar:RELEASE82, org.netbeans.api:org-openide-dialogs:jar:RELEASE82, org.netbeans.api:org-openide-nodes:jar:RELEASE82, org.netbeans.api:org-netbeans-api-annotations-common:jar:RELEASE82: Could not find artifact org.netbeans.api:org-netbeans-modules-nbjunit:jar:RELEASE82 in netbeans (http://bits.netbeans.org/nexus/content/groups/netbeans/) -> [Help 1]
`

It seems that the RELEASE82 is not available on bit.netbeans.org anymore:
[http://bits.netbeans.org/maven2/org/netbeans/api/org-openide-filesystems/RELEASE802/org-openide-filesystems-RELEASE802.pom](http://bits.netbeans.org/maven2/org/netbeans/api/org-openide-filesystems/RELEASE802/org-openide-filesystems-RELEASE802.pom)

As mentioned in #39 the netbeans platform version should probably updated:
```
<netbeans.version>RELEASE110</netbeans.version>
```

Are there any reasons why to not update to a new netbeans platform version?

**Comment by alextrosta** [comment]
@htmoia Have you found any ways to work around this?

**Comment by liuqiyuan** [comment]
any updates?

**Comment by mbastian** [comment]
Thanks, this is now fixed in `master` and in sync with the upcoming Gephi 0.9.3 version. It relies on the `RELEASE130` version of Netbeans Platform. Once the Gephi 0.9.3 version is released, we'll also make a gephi-toolkit release.
