### ISSUE TITLE
gephi-toolkit-0.9.2-all.jar couldn't be added into current netbeans' module project

### ISSUE THREAD

**Issue by askua** [gephi/gephi-toolkit#44]
Dear Gephi Group,
       I'm develping a netbeans module project that need use toolkit to draw a graph !
      I only added open source code package org.gephi.toolkit.demos;
       When I add gephi-toolkit-0.9.2.jar into my netbeans module project, I could successfully compile the project,
![image](https://user-images.githubusercontent.com/20092292/118462306-1d6e9900-b731-11eb-920e-39502753749a.png)

But I failed to run it, 
the IDE told me:  java.lang.ClassNotFoundException

Error Note:
java.lang.ClassNotFoundException: org.netbeans.modules.masterfs.watcher.Watcher@ModuleCL@1b5dab8b[com.ml.predict]:jar:file:/D:/JavaProjects/CIF-DL/build/cluster/modules/ext/gephi-toolkit-0.9.2-all.jar!/ not a subclass of org.netbeans.modules.masterfs.watcher.Watcher@ModuleCL@1f1c9b7a[org.netbeans.modules.masterfs]:jar:file:/E:/CIFLog/platform/modules/org-netbeans-modules-masterfs.jar!/
![image](https://user-images.githubusercontent.com/20092292/118463680-a0dcba00-b732-11eb-9946-b08240416cbd.png)

My  IDE Environment has 
jdk1.8.0_192，Netbeans 8.2,  apache-maven-3.6.0

I didn't know how to solve it, 
I recompile the gephi-toolkit.jar , but it doesn't work

What should I do?

**Comment by mbastian** [comment]
Hi, you should load the toolkit as a standard Maven dependency instead of loading the JAR.

```
<dependency>
    <groupId>org.gephi</groupId>
    <artifactId>gephi-toolkit</artifactId>
    <version>0.10.1</version>
</dependency>
```
