### ISSUE TITLE
Search broken in JavaDoc

### ISSUE THREAD

**Issue by nagorczak** [gephi/gephi-toolkit#46]
When using the search function (e. g. searching "PreviewProperty"), an error message is shown altough the class can perfectly be accessed via clicking through the list of all classes.

The message is `AccessDeniedprod-web-14tx00000000000001fe5ee4e-00626fa92d-319aca72-nyc3c319aca72-nyc3c-nyc3-zg03html, body, body :not(iframe) { background-color: #2c2d2d !important; border-color: #726b60 !important; color: #c7c3bc !important; }`

Accessing the doc of the class PreviewProperty via search leads to: [https://www.javadoc.io/doc/org.gephi/gephi-toolkit/latest/undefined/org/gephi/preview/api/PreviewProperty.html](https://www.javadoc.io/doc/org.gephi/gephi-toolkit/latest/undefined/org/gephi/preview/api/PreviewProperty.html )
Whereas accessing it via list of all classes, it leads to: [https://www.javadoc.io/doc/org.gephi/gephi-toolkit/latest/org/gephi/preview/api/PreviewProperty.html](https://www.javadoc.io/doc/org.gephi/gephi-toolkit/latest/org/gephi/preview/api/PreviewProperty.html)

**Comment by mbastian** [comment]
Hi @nagorczak I'm not able to reproduce this issue, let us know if it still occurs. Otherwise I'll close.

**Comment by nagorczak** [comment]
The issue still occurs. But since 0.9.7 is not the latest version anymore, the links to the latest version in my description are now working. Thus, I updated the links right now.
