### ISSUE TITLE
Data import from Oracle database 

### ISSUE THREAD

**Issue by baau** [gephi/gephi-toolkit#6]
Hi,
I am new to the gephi platform and have used Gephi toolkit for my web application, I am stuck at importing data from Oracle database and don't know how to do it. Any help is highly appreciated.

**Comment by jgebal** [comment]
I would also be happy to see ability to connect to Oracle DB directly.
I know that Oracle licence agreements do not allow to re-publish their code (JDBC drivers), but that should not be an issue to have connenctor and ask users to provide jdbc drivers themselves.

**Comment by eduramiba** [comment]
There is a Oracle importer plugin https://gephi.org/plugins/#/plugin/oracle-driver
Maybe you can try to add it to your classpath to make it work.

**Comment by aghnaurooj** [comment]
- Hi there,
I am new to the gephi platform. I am unable to find a tutorial to import data from Oracle to gephi. I have no idea how I am supposed to do this. I really need the help of someone who did it and knows how to do this. Thanks.

**Comment by eduramiba** [comment]
Hi,
Please install the official [Oracle Instant Client](https://www.oracle.com/database/technologies/instant-client/downloads.html) in your computer, which includes the driver. Then, install the plugin https://gephi.org/plugins/#/plugin/oracle-driver following instructions and then use the database import feature in Gephi. Check http://forum-gephi.org/viewtopic.php?t=922 for examples.

**Comment by aghnaurooj** [comment]
thank you so much for the much needed help.... @eduramiba

**Comment by HRTanjuang** [comment]
https://github.com/gephi/gephi-toolkit/issues/33
